<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace GPBMetadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abf010a0e6d657373616765732e70726f746f1203756e6f22070a05456d" .
            "70747922180a0a556e6f4d657373616765120a0a026e6f18012001280d32" .
            "7d0a03556e6f12250a0452656e74120a2e756e6f2e456d7074791a0f2e75" .
            "6e6f2e556e6f4d657373616765220012260a0552656c6574120f2e756e6f" .
            "2e556e6f4d6573736167651a0a2e756e6f2e456d707479220012270a0652" .
            "657475726e120f2e756e6f2e556e6f4d6573736167651a0a2e756e6f2e45" .
            "6d7074792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

