<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

namespace Uno;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>uno.UnoMessage</code>
 */
class UnoMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 no = 1;</code>
     */
    private $no = 0;

    public function __construct() {
        \GPBMetadata\Messages::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 no = 1;</code>
     * @return int
     */
    public function getNo()
    {
        return $this->no;
    }

    /**
     * Generated from protobuf field <code>uint32 no = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNo($var)
    {
        GPBUtil::checkUint32($var);
        $this->no = $var;

        return $this;
    }

}

